#### Import Statements

In [36]:
import numpy as np

import matplotlib.pyplot as plt
from scipy import datasets
from PIL import Image # for reading image files

#### 1-Dimensional Arrays (Vectors)

In [2]:
my_array = np.array([1.1, 9.2, 8.1, 4.7])

In [ ]:
my_array.shape

In [ ]:
my_array[2]

#### 2-Dimensional Arrays (Matrices)

In [7]:
array_2d = np.array([[1, 2, 3, 9], [5, 6, 7, 8]])

In [ ]:
print(f'array_2d has {array_2d.ndim} dimensions')
print(f'Its shape is {array_2d.shape}')
print(f'It has {array_2d.shape[0]} rows and {array_2d.shape[1]} columns')
print(array_2d)

#### N-Dimensional Arrays (Tensors)

In [9]:
mystery_array = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]],
                          [[7, 86, 6, 98], [5, 1, 0, 4]],
                          [[5, 36, 32, 48], [97, 0, 27, 18]]])

In [10]:
print(f'We have {mystery_array.ndim} dimensions')
print(f'The shape is {mystery_array.shape}')

We have 3 dimensions
The shape is (3, 2, 4)


In [ ]:
mystery_array[2, 1, 3]

In [ ]:
mystery_array[2, 1, :]

In [13]:
mystery_array[:, :, 0]

array([[ 0,  4],
       [ 7,  5],
       [ 5, 97]])

# NumPy Mini-Challenges

#### **Challenge 1**: Use [`.arange()`](https://numpy.org/devdocs/reference/generated/numpy.arange.html)to createa a vector `a` with values ranging from 10 to 29. You should get this:

`print(a)`

`[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]`

In [14]:
a = np.arange(10,30)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


#### **Challenge 2**: Use Python slicing techniques on `a` to:
* Create an array containing only the last 3 values of `a`
* Create a subset with only the 4th, 5th, and 6th values
* Create a subset of `a` containing all the values except for the first 12 (i.e., `[22, 23, 24, 25, 26, 27, 28, 29]`)
* Create a subset that only contains the even numbers (i.e, every second number)

In [ ]:
a[-3:]

In [ ]:
a[3:6]

In [ ]:
a[12:]

In [ ]:
a[::2]

#### **Challenge 3**:Reverse the order of the values in `a`, so that the first element comes last:

`[29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10]`


If you need a hint, you can check out this part of the [NumPy beginner's guide](
https://numpy.org/devdocs/user/absolute_beginners.html#how-to-reverse-an-array)

In [ ]:
np.flip(a)

#### **Challenge 4**: Print out all the indices of the non-zero elements in this array: [6,0,9,0,0,5,0]

In [ ]:
b = np.array([6,0,9,0,0,5,0])
nz_indices = np.nonzero(b)
nz_indices

#### **Challenge 5**: Use NumPy to generate a 3x3x3 array with random numbers

Hint: Use the [`.random()` function](https://numpy.org/doc/stable/reference/random/index.html?highlight=random#module-numpy.random)

In [ ]:
from numpy.random import random
z = random((3,3,3))
z

#### **Challenge 6**: Use [`.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) to create a vector `x` of size 9 with values spaced out evenly between 0 to 100 (both included).

In [ ]:
x = np.linspace(0, 100, num=9)
print(x)
x.shape

#### **Challenge 7**: Use [`.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) to create another vector `y` of size 9 with values between -3 to 3 (both included). Then plot `x` and `y` on a line chart using Matplotlib.

In [ ]:
y = np.linspace(start=-3, stop=3, num=9)
plt.plot(x, y)
plt.show()

#### **Challenge 8**: Use NumPy to generate an array called `noise` with shape 128x128x3 that has random values. Then use Matplotlib's [`.imshow()`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imshow.html) to display the array as an image.

In [ ]:
noise = np.random.random((128,128,3))
print(noise.shape)
plt.imshow(noise)

# Linear Algebra with Vectors

In [ ]:
v1 = np.array([4, 5, 2, 7])
v2 = np.array([2, 1, 3, 3])

In [ ]:
# Python Lists vs ndarrays
list1 = [4, 5, 2, 7]
list2 = [2, 1, 3, 3]

# Broadcasting and Scalars


In [22]:
v1 = np.array([4, 5, 2, 7])
v2 = np.array([2, 1, 3, 3])

In [ ]:
v1 + v2

In [ ]:
v1 * v2

# Matrix Multiplication with @ and .matmul()

In [ ]:
a1 = np.array([[1, 3],
               [0, 1],
               [6, 2],
               [9, 7]])

b1 = np.array([[4, 1, 3],
               [5, 8, 5]])

print(f'{a1.shape}: a has {a1.shape[0]} rows and {a1.shape[1]} columns.')
print(f'{b1.shape}: b has {b1.shape[0]} rows and {b1.shape[1]} columns.')
print('Dimensions of result: (4x2)*(2x3)=(4x3)')

**Challenge**: Let's multiply `a1` with `b1`. Looking at the wikipedia example above, work out the values for c12 and c33 on paper. Then use the [`.matmul()`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) function or the `@` operator to check your work.

In [25]:
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

In [ ]:
array_2d + 10

In [ ]:
array_2d * 56

In [32]:
a1 = np.array([[1, 3],
               [0, 1],
               [6, 2],
               [9, 7]])

b1 = np.array([[4, 1, 3],
               [5, 8, 5]])

c = np.matmul(a1, b1)
print(f'Matrix c has {c.shape[0]} rows and {c.shape[1]} columns.')
c

Matrix c has 4 rows and 3 columns.


array([[19, 25, 18],
       [ 5,  8,  5],
       [34, 22, 28],
       [71, 65, 62]])

In [ ]:
a1 @ b1

# Manipulating Images as ndarrays


In [ ]:
face = datasets.face()
plt.imshow(face)


In [ ]:
type(face)

In [ ]:
face.shape

In [ ]:
face.ndim

**Challenge**: Convert the image to black and white. The values in our `img` range from 0 to 255.
* Divide all the values by 255 to convert them to sRGB, where all the values are between 0 and 1.
* Next, multiply the sRGB array by the `grey_vals` to convert the image to grey scale.
* Finally use Matplotlib's [`.imshow()`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imshow.html) together with the colormap parameter set to gray `cmap=gray` to look at the results.

In [46]:
sRGB_array = face / 255

In [48]:
grey_vals = np.array([0.2126, 0.7152, 0.0722])

In [ ]:
face_gray = sRGB_array @ grey_vals

In [ ]:
plt.imshow(face_gray, cmap='gray')

**Challenge**: Can you manipulate the images by doing some operations on the underlying ndarrays? See if you can change the values in the ndarray so that:

1) You flip the grayscale image upside down

<img src=https://i.imgur.com/r36CigD.png>

2) Rotate the colour image

<img src=https://i.imgur.com/IiNylco.png>

3) Invert (i.e., solarize) the colour image. To do this you need to converting all the pixels to their "opposite" value, so black (0) becomes white (255).

<img src=https://i.imgur.com/cfFbuex.png>

#### Challenge Solutions

In [ ]:
plt.imshow(np.flip(face_gray), cmap='gray')

In [ ]:
plt.imshow(np.rot90(face))

In [ ]:
solar_face = 255 - face
plt.imshow(solar_face)